### ISSUE TITLE
AttributeError: 'int' object has no attribute 'replace'

### ISSUE THREAD

**Issue by arinazari** [pjsier/anki-compressor#1]
Not sure why I got this error (maybe a Python version issue?):

`anki-compressor -i all_decks.apkg -o all_decks_compressed.apkg -q 50 -b 64k
  1%|▋                                                       | 395/32352 [01:30<1:36:02,  5.55it/s]Traceback (most recent call last):
  File "/Users/[user]/.pyenv/versions/3.8.2/bin/anki-compressor", line 8, in <module>
    sys.exit(main())
  File "/Users/[user]/.pyenv/versions/3.8.2/lib/python3.8/site-packages/anki_compressor/__main__.py", line 124, in main
    update_db(conn, cur, v, 'jpg')
  File "/Users/[user]/.pyenv/versions/3.8.2/lib/python3.8/site-packages/anki_compressor/__main__.py", line 40, in update_db
    row[2].replace(filename, new_filename),
AttributeError: 'int' object has no attribute 'replace'
  1%|▋                                                       | 395/32352 [01:30<2:02:12,  4.36it/s]`

For anyone else who might run into this, I got around it by changing row[0] row[1] and row[2] to str(row[0]) etc. in the source code and it seems like it's worked.

**Comment by pjsier** [comment]
@arinazari thanks for flagging this! I didn't actually realize people were still using this. That should be a quick change, and I can clean up some other pieces since I haven't made an update in a while

**Comment by pjsier** [comment]
Should be fixed in the latest release, thanks again!
