### ISSUE TITLE
Add option to choose filetype for compressed images

### ISSUE THREAD

**Issue by pjsier** [pjsier/anki-compressor#2]
Currently images are always converted to JPG. An `argparse` flag and option could be added to select a filetype to write images in with the default still being JPG

This is a similar flag to what would work:

https://github.com/pjsier/anki-compressor/blob/8af36d832f79434ebeda5f94d1001929adcb254e/anki_compressor/__main__.py#L113-L119

and images are written here:

https://github.com/pjsier/anki-compressor/blob/8af36d832f79434ebeda5f94d1001929adcb254e/anki_compressor/__main__.py#L50-L62

The database writes would also need to be updated to account for different filetypes:

https://github.com/pjsier/anki-compressor/blob/8af36d832f79434ebeda5f94d1001929adcb254e/anki_compressor/__main__.py#L155-L159

**Comment by ronnie-llamado** [comment]
I'm interested in helping out on this issue.

**Comment by pjsier** [comment]
@ronnie-llamado sounds great! Assigning you now, feel free to post any questions here

**Comment by ronnie-llamado** [comment]
I've made some changes and drafted a pull request. Before marking it 'Ready for Review', can you provide some guidance on how to test the new feature? Do you have a test Anki package on hand?

**Comment by pjsier** [comment]
This is great! The testing situation isn't ideal, but Anki has some shared decks you can download here https://ankiweb.net/shared/decks/. You may need to download Anki and look at the results to open the generated deck and see if it's valid. I'll also run a test when reviewing the PR
