### ISSUE TITLE
Create a shorter entrypoint for running the executable

### ISSUE THREAD

**Issue by pjsier** [pjsier/anki-compressor#4]
Currently the executable name needs to be spelled out in full as `anki-compressor` to call any commands. It would probably be better to add something like `ankic` as another option in `console_scripts`, but the existing name should also be maintained

https://github.com/pjsier/anki-compressor/blob/8af36d832f79434ebeda5f94d1001929adcb254e/setup.py#L24-L26

**Comment by milindchauhan** [comment]
Hey I'd like to work on this issue. As you can see I already made a PR that failed a bunch of tests it seems. I thought it would be just a one line addition but didn't know how to test. Can you guide me as to what to do next?

**Comment by pjsier** [comment]
Sure! It failed on the formatting checks with `black`. You can run the `black` command locally to fix the formatting errors and then it should pass

**Comment by milindchauhan** [comment]
thanks for the help. Seems to work now. Should I make a new PR or push that commit to the previous PR?

**Comment by pjsier** [comment]
Yeah, you can go ahead and push the new commit to the same branch and that will update your PR

**Comment by milindchauhan** [comment]
Done 👍

**Comment by pjsier** [comment]
Closed by #6, thanks @milindchauhan !
